### ISSUE TITLE
[Enhancement] Easy checking of CLI output

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#22]
**What would you like to be added**:

An easy, declarative way to check that output from the result of a command, script, or CLI:

1. equals what I define (i.e., it has nothing more than what I state and looks precisely what I define)
2. contains what I define (i.e., it may have more than what I state and it may be found anywhere in the output)

**Why is this needed**:

We need a way to test things like `kyverno apply` and `kyverno jp` reliably outside the confines of unit tests and from an end user perspective.

**Comment by shubham-cmyk** [comment]
@chipzoller 

Please help me to understand this issue.

What i get here is I need to modify the `kyverno cli` maybe we could add a flag i.e `-e2e`. 
So when we use command  : 

`kyverno apply /path/to/policy.yaml --resource /path/to/resource.yaml -e2e`

is passed the test would now run in the live k8s cluster.

**Comment by chipzoller** [comment]
It seems like discussion is underway in #35.
