### ISSUE TITLE
[Enhancement] YAML validation of a `TestStep` file

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#24]
When kuttl parses a `TestStep` file, there is currently no validation performed to ensure basic things such as:

1. a field is specified but unrecognized / indentation errors
2. a required field is missing
3. a referenced file in a field cannot be located

We need to add some of these basic validation checks to ensure authors of these kuttl tests don't waste time chasing simple problems.

**Comment by shubham-cmyk** [comment]
@chipzoller 
Will these issues be solved in the LFX duration or I could start working on this now?  Since I am applying for the LFX 2023.

**Comment by chipzoller** [comment]
These are all reserved for the LFX mentorship.
