### ISSUE TITLE
[Enhancement] Aggregate and display failures at the bottom of output

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#25]
When a TestCase is run which contains a large number of tests, should any of those tests fail they are printed along with passed tests in what could be a very long list. When the number of tests becomes quite large, for example over 100, one must carefully scan every entry to see what the failed tests are. This is tedious and can result in tests being missed.

When any tests fail in a TestCase containing multiple tests, aggregate and display the failed tests together as the final portion of the output. Do not change any of the existing output, just add a section at the bottom which groups only the failed tests together.

**Comment by chipzoller** [comment]
Please understand this issue is part of an LFX mentorship, which is an application-based process. Application is no guarantee of selection. The mentee who is selected for this mentorship will be given priority over any PRs.

That said, please refrain from posting screenshots of text and terminal output. Please use proper code blocks. The output shown does not appear to include any successful tests so it is difficult to determine what the end behavior is.

**Comment by 0x-chaitu** [comment]
Ah okay.
Sorry I thought we could try working on it.
Learnt a lot though.
