### ISSUE TITLE
[Enhancement] Parameter to halt testing upon the first failure

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#26]
When tests are performed serially as they are in Kyverno's case, no tests should fail. For any test to fail indicates a problem somewhere. Continuing to test other tests may often be undesirable as it wastes time and processing in order for a user/contributor to know what may be broken and requires remediation.

Add a parameter to a TestCase file to allow the user to indicate that testing should not proceed upon the first test failure.

**Comment by shubham-cmyk** [comment]
@chipzoller  I got a little confused over this.
In a TestSuite there would be multiple TestCase and 
In a TestCase there are multiple Steps.

If I am right you are referring to the failure of the steps right?

**Comment by chipzoller** [comment]
Failure of a step triggers failure of the test case. With this enhancement, a new field can indicate that failure of a test case halts any further testing.

**Comment by shubham-cmyk** [comment]
Yes got it. Other TestCase should still run right

**Comment by chipzoller** [comment]
No, that's what I just said. When the parameter enabled, a failure of one test case causes no further test cases to run.

**Comment by shubham-cmyk** [comment]
Now I got it.
